config/routes.rb
Rails.application.routes.draw do
  root 'entries#search'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  resources :entries, except: [:destroy] do
    get :search, on: :collection
    post :invoke_search, on: :collection
    resources :reference_images, only: [:new, :destroy] do
      post :create_multiple, on: :collection
    end
  end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :reference_images
end

app/models/reference_image.rb
class ReferenceImage < ActiveRecord::Base
  extend FriendlyId
  belongs_to :entry
  mount_uploader :image, ReferenceImageUploader
  friendly_id :file_name, use: :slugged

  validates :image, presence: true

  after_commit :save_to_search_apis, on: :create
  after_commit :delete_from_search_apis, on: :destroy

  def file_name
    File.basename(image.file.path) if image && image.file
  end

  def self.search_apis(file)
    response = MoodstockApi.new.search(file)
    
    if response['id']
      friendly.find response['id']
    end

  end

  private

  def save_to_search_apis
    MoodstockApi.new.save_reference self
  end

  def delete_from_search_apis
    MoodstockApi.new.delete_reference self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :load_entry, only: [:edit, :update, :show]

  def index
    @entries = Entry.all
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new strong_params

    if @entry.save
      redirect_to entry_path(@entry)
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @entry.update_attributes strong_params
      redirect_to entry_path(@entry)
    else
      render :edit
    end
  end

  def search
  end

  def invoke_search
    if reference_image = ReferenceImage.search_apis(params[:search_image])
      redirect_to entry_path(reference_image.entry)
    else
      flash[:error] = 'No matches found!'
      render :search
    end
  end

  private

  def load_entry
    @entry = Entry.find params[:id]
  end

  def strong_params
    params.require(:entry).permit :name
  end

end

app/controllers/reference_images_controller.rb
class ReferenceImagesController < ApplicationController
  before_action :load_entry
  before_action :load_reference_image, only: [:destroy]

  def new
    @reference_image = @entry.reference_images.new
  end

  def create_multiple
    ReferenceImage.transaction do

      params[:images].each do |file|
        @entry.reference_images.create! image: file
      end
      
    end
    
    
    redirect_to entry_path(@entry)
  end

  def destroy
    @reference_image.destroy!
    redirect_to entry_path(@entry)
  end
  
  private

  def load_entry
    @entry = Entry.find params[:entry_id]
  end

  def load_reference_image
    @reference_image = @entry.reference_images.friendly.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_form.html.slim
= form_for(@entry, html:{class: 'form'}) do |f|
  = render 'shared/form_error_summary', f: f
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit "#{f.object.new_record? ? 'Create and add images' : 'Update entry'}", class: 'submit'
  hr
  a href='#{entries_path}' back to entries

app/views/entries/edit.html.slim
h1 Update entry
section = render 'form'

app/views/entries/index.html.slim
h1 Entries
p = link_to 'Create new entry', new_entry_path
section: table.table
  thead: tr
    th name
    th images
  tbody
    - @entries.each do |entry|
      tr
        td = link_to entry.name, entry_path(entry)
        td = entry.reference_images.count

app/views/entries/new.html.slim
h1 Create entry
section = render 'form'

app/views/entries/search.html.slim
section
  .jumbotron
    = form_tag(invoke_search_entries_path, class: 'form', multipart: true) do |f|
      .form-group
        = file_field_tag :search_image

      = submit_tag 'Search', class: 'submit'
  
  - if @entry
    h2 Found entry
    h3 = link_to @entry.name, @entry

app/views/entries/show.html.slim
section
  .jumbotron
    h1: a href='#{edit_entry_path(@entry)}'
      | #{@entry.name}   
      small: i.fa.fa-pencil
    p: small = link_to 'Add reference image', new_entry_reference_image_path(@entry)
  
  - if @entry.reference_images.any?  
    h2 Reference images
    .row
    - @entry.reference_images.each do |ri|
      .col-xs-6.col-md-2: .mute-heading: .image-row data-image-id='#{ri.id}'
        h3
          img src='#{ri.image.url}' class='img-responsive'
        p
          i.fa.fa-clock-o
          |   created #{time_ago_in_words(ri.created_at)} ago
        p = link_to 'delete',  entry_reference_image_path(@entry, ri),  method: :delete, data: { confirm: 'Are you sure?' }

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  .messages.alert class="alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
    button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'ImageRecogniser', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li = link_to 'Entries', entries_path
li = link_to 'New entry', new_entry_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'ImageRecogniser'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'ImageRecogniser'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags

  body class="controller-action-#{params[:controller]}-#{params[:action]}"
    header
      == render 'layouts/navigation'
    main[role="main"]
      .container
        == render 'layouts/messages'
        == content_for?(:content) ? yield(:content) : yield

app/views/reference_images/_form.html.slim
= form_tag(create_multiple_entry_reference_images_path(@entry, @reference_image), class: 'form', multipart: true) do
  .form-group
    = file_field_tag 'images[]', multiple: true

  = submit_tag 'Create image', class: 'submit'
  hr
  a href='#{entry_path(@entry)}' back to entry

app/views/reference_images/new.html.slim
h1 Create reference image for #{@entry.name}
section = render 'form'

app/views/shared/_form_error_summary.html.slim
- if f.object.errors.any?
  .alert.alert-danger
    ul.list-unstyled
      - f.object.errors.full_messages.each do |msg|
        li = msg